package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.CityTemperature;

public interface CityTemperatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    int insert(CityTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    int insertSelective(CityTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    CityTemperature selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    int updateByPrimaryKeySelective(CityTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    int updateByPrimaryKey(CityTemperature record);
}