package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityTimeSection;

public interface ElectricityTimeSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_time_section
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_time_section
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    int insert(ElectricityTimeSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_time_section
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    int insertSelective(ElectricityTimeSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_time_section
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    ElectricityTimeSection selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_time_section
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityTimeSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_time_section
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    int updateByPrimaryKey(ElectricityTimeSection record);
}