package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceStructureRule;

public interface ElectricityPriceStructureRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure_rule
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure_rule
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    int insert(ElectricityPriceStructureRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure_rule
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    int insertSelective(ElectricityPriceStructureRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure_rule
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    ElectricityPriceStructureRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure_rule
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityPriceStructureRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure_rule
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    int updateByPrimaryKey(ElectricityPriceStructureRule record);
}