package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceDetail;

public interface ElectricityPriceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Fri Apr 29 17:35:29 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Fri Apr 29 17:35:29 CST 2022
     */
    int insert(ElectricityPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Fri Apr 29 17:35:29 CST 2022
     */
    int insertSelective(ElectricityPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Fri Apr 29 17:35:29 CST 2022
     */
    ElectricityPriceDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Fri Apr 29 17:35:29 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Fri Apr 29 17:35:29 CST 2022
     */
    int updateByPrimaryKey(ElectricityPriceDetail record);
}