package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceEquipment;

public interface ElectricityPriceEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_equipment
     *
     * @mbg.generated Tue May 17 09:36:34 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_equipment
     *
     * @mbg.generated Tue May 17 09:36:34 CST 2022
     */
    int insert(ElectricityPriceEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_equipment
     *
     * @mbg.generated Tue May 17 09:36:34 CST 2022
     */
    int insertSelective(ElectricityPriceEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_equipment
     *
     * @mbg.generated Tue May 17 09:36:34 CST 2022
     */
    ElectricityPriceEquipment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_equipment
     *
     * @mbg.generated Tue May 17 09:36:34 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityPriceEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_equipment
     *
     * @mbg.generated Tue May 17 09:36:34 CST 2022
     */
    int updateByPrimaryKey(ElectricityPriceEquipment record);
}