package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceRule;

public interface ElectricityPriceRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_rule
     *
     * @mbg.generated Fri Apr 29 16:24:21 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_rule
     *
     * @mbg.generated Fri Apr 29 16:24:21 CST 2022
     */
    int insert(ElectricityPriceRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_rule
     *
     * @mbg.generated Fri Apr 29 16:24:21 CST 2022
     */
    int insertSelective(ElectricityPriceRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_rule
     *
     * @mbg.generated Fri Apr 29 16:24:21 CST 2022
     */
    ElectricityPriceRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_rule
     *
     * @mbg.generated Fri Apr 29 16:24:21 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityPriceRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_rule
     *
     * @mbg.generated Fri Apr 29 16:24:21 CST 2022
     */
    int updateByPrimaryKey(ElectricityPriceRule record);
}