package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceStructure;

public interface ElectricityPriceStructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    int insert(ElectricityPriceStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    int insertSelective(ElectricityPriceStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    ElectricityPriceStructure selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityPriceStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_structure
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    int updateByPrimaryKey(ElectricityPriceStructure record);
}