package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceDetail;

public interface ElectricityPriceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    int insert(ElectricityPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    int insertSelective(ElectricityPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    ElectricityPriceDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    int updateByPrimaryKeySelective(ElectricityPriceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_detail
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    int updateByPrimaryKey(ElectricityPriceDetail record);
}