package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceSeason;

public interface ElectricityPriceSeasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    int insert(ElectricityPriceSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    int insertSelective(ElectricityPriceSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    ElectricityPriceSeason selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    int updateByPrimaryKeySelective(ElectricityPriceSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    int updateByPrimaryKey(ElectricityPriceSeason record);
}