package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityFactorCharge;

public interface ElectricityFactorChargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_factor_charge
     *
     * @mbg.generated Fri Apr 29 17:34:55 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_factor_charge
     *
     * @mbg.generated Fri Apr 29 17:34:55 CST 2022
     */
    int insert(ElectricityFactorCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_factor_charge
     *
     * @mbg.generated Fri Apr 29 17:34:55 CST 2022
     */
    int insertSelective(ElectricityFactorCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_factor_charge
     *
     * @mbg.generated Fri Apr 29 17:34:55 CST 2022
     */
    ElectricityFactorCharge selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_factor_charge
     *
     * @mbg.generated Fri Apr 29 17:34:55 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityFactorCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_factor_charge
     *
     * @mbg.generated Fri Apr 29 17:34:55 CST 2022
     */
    int updateByPrimaryKey(ElectricityFactorCharge record);
}