package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceVersion;

public interface ElectricityPriceVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_version
     *
     * @mbg.generated Fri Apr 29 16:17:45 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_version
     *
     * @mbg.generated Fri Apr 29 16:17:45 CST 2022
     */
    int insert(ElectricityPriceVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_version
     *
     * @mbg.generated Fri Apr 29 16:17:45 CST 2022
     */
    int insertSelective(ElectricityPriceVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_version
     *
     * @mbg.generated Fri Apr 29 16:17:45 CST 2022
     */
    ElectricityPriceVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_version
     *
     * @mbg.generated Fri Apr 29 16:17:45 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityPriceVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_version
     *
     * @mbg.generated Fri Apr 29 16:17:45 CST 2022
     */
    int updateByPrimaryKey(ElectricityPriceVersion record);
}