package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricityPriceDictionary;

public interface ElectricityPriceDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_dictionary
     *
     * @mbg.generated Fri Apr 29 17:37:04 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_dictionary
     *
     * @mbg.generated Fri Apr 29 17:37:04 CST 2022
     */
    int insert(ElectricityPriceDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_dictionary
     *
     * @mbg.generated Fri Apr 29 17:37:04 CST 2022
     */
    int insertSelective(ElectricityPriceDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_dictionary
     *
     * @mbg.generated Fri Apr 29 17:37:04 CST 2022
     */
    ElectricityPriceDictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_dictionary
     *
     * @mbg.generated Fri Apr 29 17:37:04 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricityPriceDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_price_dictionary
     *
     * @mbg.generated Fri Apr 29 17:37:04 CST 2022
     */
    int updateByPrimaryKey(ElectricityPriceDictionary record);
}