package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.ElectricitySeasonSection;

public interface ElectricitySeasonSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_season_section
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_season_section
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    int insert(ElectricitySeasonSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_season_section
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    int insertSelective(ElectricitySeasonSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_season_section
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    ElectricitySeasonSection selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_season_section
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    int updateByPrimaryKeySelective(ElectricitySeasonSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electricity_season_section
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    int updateByPrimaryKey(ElectricitySeasonSection record);
}