package com.enn.energy.price.dal.mapper.mbg;

import com.enn.energy.price.dal.po.mbg.SystemTree;

public interface SystemTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_tree
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    int deleteByPrimaryKey(Long nodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_tree
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    int insert(SystemTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_tree
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    int insertSelective(SystemTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_tree
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    SystemTree selectByPrimaryKey(Long nodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_tree
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    int updateByPrimaryKeySelective(SystemTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_tree
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    int updateByPrimaryKey(SystemTree record);
}