package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class CityTemperature {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_temperature.id
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_temperature.area_code
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_temperature.date
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_temperature.temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_temperature.create_time
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_temperature.update_time
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_temperature.id
     *
     * @return the value of city_temperature.id
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_temperature.id
     *
     * @param id the value for city_temperature.id
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_temperature.area_code
     *
     * @return the value of city_temperature.area_code
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_temperature.area_code
     *
     * @param areaCode the value for city_temperature.area_code
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_temperature.date
     *
     * @return the value of city_temperature.date
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_temperature.date
     *
     * @param date the value for city_temperature.date
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_temperature.temperature
     *
     * @return the value of city_temperature.temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_temperature.temperature
     *
     * @param temperature the value for city_temperature.temperature
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_temperature.create_time
     *
     * @return the value of city_temperature.create_time
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_temperature.create_time
     *
     * @param createTime the value for city_temperature.create_time
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_temperature.update_time
     *
     * @return the value of city_temperature.update_time
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_temperature.update_time
     *
     * @param updateTime the value for city_temperature.update_time
     *
     * @mbg.generated Fri Apr 29 17:26:28 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}