package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class CityWeather {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_weather.id
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_weather.area_code
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_weather.date
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_weather.temp_day
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    private String tempDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_weather.temp_night
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    private String tempNight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_weather.create_time
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_weather.update_time
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_weather.id
     *
     * @return the value of city_weather.id
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_weather.id
     *
     * @param id the value for city_weather.id
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_weather.area_code
     *
     * @return the value of city_weather.area_code
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_weather.area_code
     *
     * @param areaCode the value for city_weather.area_code
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_weather.date
     *
     * @return the value of city_weather.date
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_weather.date
     *
     * @param date the value for city_weather.date
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_weather.temp_day
     *
     * @return the value of city_weather.temp_day
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public String getTempDay() {
        return tempDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_weather.temp_day
     *
     * @param tempDay the value for city_weather.temp_day
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public void setTempDay(String tempDay) {
        this.tempDay = tempDay == null ? null : tempDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_weather.temp_night
     *
     * @return the value of city_weather.temp_night
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public String getTempNight() {
        return tempNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_weather.temp_night
     *
     * @param tempNight the value for city_weather.temp_night
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public void setTempNight(String tempNight) {
        this.tempNight = tempNight == null ? null : tempNight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_weather.create_time
     *
     * @return the value of city_weather.create_time
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_weather.create_time
     *
     * @param createTime the value for city_weather.create_time
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_weather.update_time
     *
     * @return the value of city_weather.update_time
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_weather.update_time
     *
     * @param updateTime the value for city_weather.update_time
     *
     * @mbg.generated Sat May 07 11:04:24 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}