package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class ElectricitySeasonSection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.structure_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private String structureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.structure_rule_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private String structureRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.season_section_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private String seasonSectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.season_section_name
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private String seasonSectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.sea_start_date
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private String seaStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.sea_end_date
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private String seaEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.state
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.create_time
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_season_section.update_time
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.id
     *
     * @return the value of electricity_season_section.id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.id
     *
     * @param id the value for electricity_season_section.id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.structure_id
     *
     * @return the value of electricity_season_section.structure_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public String getStructureId() {
        return structureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.structure_id
     *
     * @param structureId the value for electricity_season_section.structure_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setStructureId(String structureId) {
        this.structureId = structureId == null ? null : structureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.structure_rule_id
     *
     * @return the value of electricity_season_section.structure_rule_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public String getStructureRuleId() {
        return structureRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.structure_rule_id
     *
     * @param structureRuleId the value for electricity_season_section.structure_rule_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setStructureRuleId(String structureRuleId) {
        this.structureRuleId = structureRuleId == null ? null : structureRuleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.season_section_id
     *
     * @return the value of electricity_season_section.season_section_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public String getSeasonSectionId() {
        return seasonSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.season_section_id
     *
     * @param seasonSectionId the value for electricity_season_section.season_section_id
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setSeasonSectionId(String seasonSectionId) {
        this.seasonSectionId = seasonSectionId == null ? null : seasonSectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.season_section_name
     *
     * @return the value of electricity_season_section.season_section_name
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public String getSeasonSectionName() {
        return seasonSectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.season_section_name
     *
     * @param seasonSectionName the value for electricity_season_section.season_section_name
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setSeasonSectionName(String seasonSectionName) {
        this.seasonSectionName = seasonSectionName == null ? null : seasonSectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.sea_start_date
     *
     * @return the value of electricity_season_section.sea_start_date
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public String getSeaStartDate() {
        return seaStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.sea_start_date
     *
     * @param seaStartDate the value for electricity_season_section.sea_start_date
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setSeaStartDate(String seaStartDate) {
        this.seaStartDate = seaStartDate == null ? null : seaStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.sea_end_date
     *
     * @return the value of electricity_season_section.sea_end_date
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public String getSeaEndDate() {
        return seaEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.sea_end_date
     *
     * @param seaEndDate the value for electricity_season_section.sea_end_date
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setSeaEndDate(String seaEndDate) {
        this.seaEndDate = seaEndDate == null ? null : seaEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.state
     *
     * @return the value of electricity_season_section.state
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.state
     *
     * @param state the value for electricity_season_section.state
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.create_time
     *
     * @return the value of electricity_season_section.create_time
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.create_time
     *
     * @param createTime the value for electricity_season_section.create_time
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_season_section.update_time
     *
     * @return the value of electricity_season_section.update_time
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_season_section.update_time
     *
     * @param updateTime the value for electricity_season_section.update_time
     *
     * @mbg.generated Fri Apr 29 17:18:48 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}