package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class ElectricityPriceStructureRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.structure_id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private String structureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.structure_rule_id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private String structureRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.industries
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private String industries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.strategies
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private String strategies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.voltage_levels
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private String voltageLevels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.state
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.create_time
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure_rule.update_time
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.id
     *
     * @return the value of electricity_price_structure_rule.id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.id
     *
     * @param id the value for electricity_price_structure_rule.id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.structure_id
     *
     * @return the value of electricity_price_structure_rule.structure_id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public String getStructureId() {
        return structureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.structure_id
     *
     * @param structureId the value for electricity_price_structure_rule.structure_id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setStructureId(String structureId) {
        this.structureId = structureId == null ? null : structureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.structure_rule_id
     *
     * @return the value of electricity_price_structure_rule.structure_rule_id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public String getStructureRuleId() {
        return structureRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.structure_rule_id
     *
     * @param structureRuleId the value for electricity_price_structure_rule.structure_rule_id
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setStructureRuleId(String structureRuleId) {
        this.structureRuleId = structureRuleId == null ? null : structureRuleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.industries
     *
     * @return the value of electricity_price_structure_rule.industries
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public String getIndustries() {
        return industries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.industries
     *
     * @param industries the value for electricity_price_structure_rule.industries
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setIndustries(String industries) {
        this.industries = industries == null ? null : industries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.strategies
     *
     * @return the value of electricity_price_structure_rule.strategies
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public String getStrategies() {
        return strategies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.strategies
     *
     * @param strategies the value for electricity_price_structure_rule.strategies
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setStrategies(String strategies) {
        this.strategies = strategies == null ? null : strategies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.voltage_levels
     *
     * @return the value of electricity_price_structure_rule.voltage_levels
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public String getVoltageLevels() {
        return voltageLevels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.voltage_levels
     *
     * @param voltageLevels the value for electricity_price_structure_rule.voltage_levels
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setVoltageLevels(String voltageLevels) {
        this.voltageLevels = voltageLevels == null ? null : voltageLevels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.state
     *
     * @return the value of electricity_price_structure_rule.state
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.state
     *
     * @param state the value for electricity_price_structure_rule.state
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.create_time
     *
     * @return the value of electricity_price_structure_rule.create_time
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.create_time
     *
     * @param createTime the value for electricity_price_structure_rule.create_time
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure_rule.update_time
     *
     * @return the value of electricity_price_structure_rule.update_time
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure_rule.update_time
     *
     * @param updateTime the value for electricity_price_structure_rule.update_time
     *
     * @mbg.generated Fri Apr 29 16:22:07 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}