package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class ElectricityPriceStructure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.structure_id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String structureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.structure_name
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String structureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.province_code
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.city_codes
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String cityCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.district_codes
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String districtCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.state
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.parentId
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.version_id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.creator
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.updator
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private String updator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.create_time
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_structure.update_time
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.id
     *
     * @return the value of electricity_price_structure.id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.id
     *
     * @param id the value for electricity_price_structure.id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.structure_id
     *
     * @return the value of electricity_price_structure.structure_id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getStructureId() {
        return structureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.structure_id
     *
     * @param structureId the value for electricity_price_structure.structure_id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setStructureId(String structureId) {
        this.structureId = structureId == null ? null : structureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.structure_name
     *
     * @return the value of electricity_price_structure.structure_name
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getStructureName() {
        return structureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.structure_name
     *
     * @param structureName the value for electricity_price_structure.structure_name
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setStructureName(String structureName) {
        this.structureName = structureName == null ? null : structureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.province_code
     *
     * @return the value of electricity_price_structure.province_code
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.province_code
     *
     * @param provinceCode the value for electricity_price_structure.province_code
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.city_codes
     *
     * @return the value of electricity_price_structure.city_codes
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getCityCodes() {
        return cityCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.city_codes
     *
     * @param cityCodes the value for electricity_price_structure.city_codes
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setCityCodes(String cityCodes) {
        this.cityCodes = cityCodes == null ? null : cityCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.district_codes
     *
     * @return the value of electricity_price_structure.district_codes
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getDistrictCodes() {
        return districtCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.district_codes
     *
     * @param districtCodes the value for electricity_price_structure.district_codes
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setDistrictCodes(String districtCodes) {
        this.districtCodes = districtCodes == null ? null : districtCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.state
     *
     * @return the value of electricity_price_structure.state
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.state
     *
     * @param state the value for electricity_price_structure.state
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.parentId
     *
     * @return the value of electricity_price_structure.parentId
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.parentId
     *
     * @param parentid the value for electricity_price_structure.parentId
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.version_id
     *
     * @return the value of electricity_price_structure.version_id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.version_id
     *
     * @param versionId the value for electricity_price_structure.version_id
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.creator
     *
     * @return the value of electricity_price_structure.creator
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.creator
     *
     * @param creator the value for electricity_price_structure.creator
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.updator
     *
     * @return the value of electricity_price_structure.updator
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.updator
     *
     * @param updator the value for electricity_price_structure.updator
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.create_time
     *
     * @return the value of electricity_price_structure.create_time
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.create_time
     *
     * @param createTime the value for electricity_price_structure.create_time
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_structure.update_time
     *
     * @return the value of electricity_price_structure.update_time
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_structure.update_time
     *
     * @param updateTime the value for electricity_price_structure.update_time
     *
     * @mbg.generated Fri Apr 29 16:21:05 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}