package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class ElectricityTimeSection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.season_section_id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private String seasonSectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.time_section_id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private String timeSectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.start_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.end_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.periods
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private String periods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.state
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.compare
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private String compare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.temperature
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.create_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_time_section.update_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.id
     *
     * @return the value of electricity_time_section.id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.id
     *
     * @param id the value for electricity_time_section.id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.season_section_id
     *
     * @return the value of electricity_time_section.season_section_id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public String getSeasonSectionId() {
        return seasonSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.season_section_id
     *
     * @param seasonSectionId the value for electricity_time_section.season_section_id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setSeasonSectionId(String seasonSectionId) {
        this.seasonSectionId = seasonSectionId == null ? null : seasonSectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.time_section_id
     *
     * @return the value of electricity_time_section.time_section_id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public String getTimeSectionId() {
        return timeSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.time_section_id
     *
     * @param timeSectionId the value for electricity_time_section.time_section_id
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setTimeSectionId(String timeSectionId) {
        this.timeSectionId = timeSectionId == null ? null : timeSectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.start_time
     *
     * @return the value of electricity_time_section.start_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.start_time
     *
     * @param startTime the value for electricity_time_section.start_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.end_time
     *
     * @return the value of electricity_time_section.end_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.end_time
     *
     * @param endTime the value for electricity_time_section.end_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.periods
     *
     * @return the value of electricity_time_section.periods
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public String getPeriods() {
        return periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.periods
     *
     * @param periods the value for electricity_time_section.periods
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setPeriods(String periods) {
        this.periods = periods == null ? null : periods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.state
     *
     * @return the value of electricity_time_section.state
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.state
     *
     * @param state the value for electricity_time_section.state
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.compare
     *
     * @return the value of electricity_time_section.compare
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public String getCompare() {
        return compare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.compare
     *
     * @param compare the value for electricity_time_section.compare
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setCompare(String compare) {
        this.compare = compare == null ? null : compare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.temperature
     *
     * @return the value of electricity_time_section.temperature
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.temperature
     *
     * @param temperature the value for electricity_time_section.temperature
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.create_time
     *
     * @return the value of electricity_time_section.create_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.create_time
     *
     * @param createTime the value for electricity_time_section.create_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_time_section.update_time
     *
     * @return the value of electricity_time_section.update_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_time_section.update_time
     *
     * @param updateTime the value for electricity_time_section.update_time
     *
     * @mbg.generated Sat Apr 30 13:15:44 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}