package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class ElectricityPriceSeason {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.season_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private String seasonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.rule_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private String ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.version_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private String versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private String season;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.sea_start_date
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private String seaStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.sea_end_date
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private String seaEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.pricing_method
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private String pricingMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.state
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.create_time
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_season.update_time
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.id
     *
     * @return the value of electricity_price_season.id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.id
     *
     * @param id the value for electricity_price_season.id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.season_id
     *
     * @return the value of electricity_price_season.season_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public String getSeasonId() {
        return seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.season_id
     *
     * @param seasonId the value for electricity_price_season.season_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setSeasonId(String seasonId) {
        this.seasonId = seasonId == null ? null : seasonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.rule_id
     *
     * @return the value of electricity_price_season.rule_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.rule_id
     *
     * @param ruleId the value for electricity_price_season.rule_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.version_id
     *
     * @return the value of electricity_price_season.version_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.version_id
     *
     * @param versionId the value for electricity_price_season.version_id
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.season
     *
     * @return the value of electricity_price_season.season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public String getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.season
     *
     * @param season the value for electricity_price_season.season
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setSeason(String season) {
        this.season = season == null ? null : season.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.sea_start_date
     *
     * @return the value of electricity_price_season.sea_start_date
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public String getSeaStartDate() {
        return seaStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.sea_start_date
     *
     * @param seaStartDate the value for electricity_price_season.sea_start_date
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setSeaStartDate(String seaStartDate) {
        this.seaStartDate = seaStartDate == null ? null : seaStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.sea_end_date
     *
     * @return the value of electricity_price_season.sea_end_date
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public String getSeaEndDate() {
        return seaEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.sea_end_date
     *
     * @param seaEndDate the value for electricity_price_season.sea_end_date
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setSeaEndDate(String seaEndDate) {
        this.seaEndDate = seaEndDate == null ? null : seaEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.pricing_method
     *
     * @return the value of electricity_price_season.pricing_method
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public String getPricingMethod() {
        return pricingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.pricing_method
     *
     * @param pricingMethod the value for electricity_price_season.pricing_method
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setPricingMethod(String pricingMethod) {
        this.pricingMethod = pricingMethod == null ? null : pricingMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.state
     *
     * @return the value of electricity_price_season.state
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.state
     *
     * @param state the value for electricity_price_season.state
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.create_time
     *
     * @return the value of electricity_price_season.create_time
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.create_time
     *
     * @param createTime the value for electricity_price_season.create_time
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_season.update_time
     *
     * @return the value of electricity_price_season.update_time
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_season.update_time
     *
     * @param updateTime the value for electricity_price_season.update_time
     *
     * @mbg.generated Wed Dec 01 17:21:26 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}