package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class ElectricityPriceDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_dictionary.id
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_dictionary.code
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_dictionary.name
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_dictionary.type
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_dictionary.type_desc
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    private String typeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_dictionary.state
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_dictionary.create_time
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_dictionary.update_time
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_dictionary.id
     *
     * @return the value of electricity_price_dictionary.id
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_dictionary.id
     *
     * @param id the value for electricity_price_dictionary.id
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_dictionary.code
     *
     * @return the value of electricity_price_dictionary.code
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_dictionary.code
     *
     * @param code the value for electricity_price_dictionary.code
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_dictionary.name
     *
     * @return the value of electricity_price_dictionary.name
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_dictionary.name
     *
     * @param name the value for electricity_price_dictionary.name
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_dictionary.type
     *
     * @return the value of electricity_price_dictionary.type
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_dictionary.type
     *
     * @param type the value for electricity_price_dictionary.type
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_dictionary.type_desc
     *
     * @return the value of electricity_price_dictionary.type_desc
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_dictionary.type_desc
     *
     * @param typeDesc the value for electricity_price_dictionary.type_desc
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc == null ? null : typeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_dictionary.state
     *
     * @return the value of electricity_price_dictionary.state
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_dictionary.state
     *
     * @param state the value for electricity_price_dictionary.state
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_dictionary.create_time
     *
     * @return the value of electricity_price_dictionary.create_time
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_dictionary.create_time
     *
     * @param createTime the value for electricity_price_dictionary.create_time
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_dictionary.update_time
     *
     * @return the value of electricity_price_dictionary.update_time
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_dictionary.update_time
     *
     * @param updateTime the value for electricity_price_dictionary.update_time
     *
     * @mbg.generated Tue Nov 30 14:11:02 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}