package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class ElectricityPriceEquipment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.equipment_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private String equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.equipment_name
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private String equipmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.rule_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private String ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.version_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private String versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.tenant
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private String tenant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.system_code
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private String systemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.state
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.create_time
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_equipment.update_time
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.id
     *
     * @return the value of electricity_price_equipment.id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.id
     *
     * @param id the value for electricity_price_equipment.id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.equipment_id
     *
     * @return the value of electricity_price_equipment.equipment_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.equipment_id
     *
     * @param equipmentId the value for electricity_price_equipment.equipment_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId == null ? null : equipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.equipment_name
     *
     * @return the value of electricity_price_equipment.equipment_name
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.equipment_name
     *
     * @param equipmentName the value for electricity_price_equipment.equipment_name
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.rule_id
     *
     * @return the value of electricity_price_equipment.rule_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.rule_id
     *
     * @param ruleId the value for electricity_price_equipment.rule_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.version_id
     *
     * @return the value of electricity_price_equipment.version_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.version_id
     *
     * @param versionId the value for electricity_price_equipment.version_id
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.tenant
     *
     * @return the value of electricity_price_equipment.tenant
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public String getTenant() {
        return tenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.tenant
     *
     * @param tenant the value for electricity_price_equipment.tenant
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setTenant(String tenant) {
        this.tenant = tenant == null ? null : tenant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.system_code
     *
     * @return the value of electricity_price_equipment.system_code
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.system_code
     *
     * @param systemCode the value for electricity_price_equipment.system_code
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode == null ? null : systemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.state
     *
     * @return the value of electricity_price_equipment.state
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.state
     *
     * @param state the value for electricity_price_equipment.state
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.create_time
     *
     * @return the value of electricity_price_equipment.create_time
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.create_time
     *
     * @param createTime the value for electricity_price_equipment.create_time
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_equipment.update_time
     *
     * @return the value of electricity_price_equipment.update_time
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_equipment.update_time
     *
     * @param updateTime the value for electricity_price_equipment.update_time
     *
     * @mbg.generated Tue Dec 07 11:15:12 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}