package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class ElectricityPriceVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.version_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.version_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String versionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.province_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.province
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.city_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.city
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.district_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String districtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.district
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.tenant_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.tenant_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String tenantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.system_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String systemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.system_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String systemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.equipment_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.equipment_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String equipmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.start_date
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.end_date
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.price_type
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String priceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.bind_type
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String bindType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.state
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.create_time
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.update_time
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electricity_price_version.last_version_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    private String lastVersionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.id
     *
     * @return the value of electricity_price_version.id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.id
     *
     * @param id the value for electricity_price_version.id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.version_id
     *
     * @return the value of electricity_price_version.version_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.version_id
     *
     * @param versionId the value for electricity_price_version.version_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.version_name
     *
     * @return the value of electricity_price_version.version_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.version_name
     *
     * @param versionName the value for electricity_price_version.version_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.province_code
     *
     * @return the value of electricity_price_version.province_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.province_code
     *
     * @param provinceCode the value for electricity_price_version.province_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.province
     *
     * @return the value of electricity_price_version.province
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.province
     *
     * @param province the value for electricity_price_version.province
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.city_code
     *
     * @return the value of electricity_price_version.city_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.city_code
     *
     * @param cityCode the value for electricity_price_version.city_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.city
     *
     * @return the value of electricity_price_version.city
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.city
     *
     * @param city the value for electricity_price_version.city
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.district_code
     *
     * @return the value of electricity_price_version.district_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.district_code
     *
     * @param districtCode the value for electricity_price_version.district_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.district
     *
     * @return the value of electricity_price_version.district
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.district
     *
     * @param district the value for electricity_price_version.district
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.tenant_id
     *
     * @return the value of electricity_price_version.tenant_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.tenant_id
     *
     * @param tenantId the value for electricity_price_version.tenant_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.tenant_name
     *
     * @return the value of electricity_price_version.tenant_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getTenantName() {
        return tenantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.tenant_name
     *
     * @param tenantName the value for electricity_price_version.tenant_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setTenantName(String tenantName) {
        this.tenantName = tenantName == null ? null : tenantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.system_code
     *
     * @return the value of electricity_price_version.system_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.system_code
     *
     * @param systemCode the value for electricity_price_version.system_code
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode == null ? null : systemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.system_name
     *
     * @return the value of electricity_price_version.system_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.system_name
     *
     * @param systemName the value for electricity_price_version.system_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.equipment_id
     *
     * @return the value of electricity_price_version.equipment_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.equipment_id
     *
     * @param equipmentId the value for electricity_price_version.equipment_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId == null ? null : equipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.equipment_name
     *
     * @return the value of electricity_price_version.equipment_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.equipment_name
     *
     * @param equipmentName the value for electricity_price_version.equipment_name
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.start_date
     *
     * @return the value of electricity_price_version.start_date
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.start_date
     *
     * @param startDate the value for electricity_price_version.start_date
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.end_date
     *
     * @return the value of electricity_price_version.end_date
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.end_date
     *
     * @param endDate the value for electricity_price_version.end_date
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.price_type
     *
     * @return the value of electricity_price_version.price_type
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.price_type
     *
     * @param priceType the value for electricity_price_version.price_type
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setPriceType(String priceType) {
        this.priceType = priceType == null ? null : priceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.bind_type
     *
     * @return the value of electricity_price_version.bind_type
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getBindType() {
        return bindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.bind_type
     *
     * @param bindType the value for electricity_price_version.bind_type
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setBindType(String bindType) {
        this.bindType = bindType == null ? null : bindType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.state
     *
     * @return the value of electricity_price_version.state
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.state
     *
     * @param state the value for electricity_price_version.state
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.create_time
     *
     * @return the value of electricity_price_version.create_time
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.create_time
     *
     * @param createTime the value for electricity_price_version.create_time
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.update_time
     *
     * @return the value of electricity_price_version.update_time
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.update_time
     *
     * @param updateTime the value for electricity_price_version.update_time
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electricity_price_version.last_version_id
     *
     * @return the value of electricity_price_version.last_version_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public String getLastVersionId() {
        return lastVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electricity_price_version.last_version_id
     *
     * @param lastVersionId the value for electricity_price_version.last_version_id
     *
     * @mbg.generated Mon Dec 20 15:38:12 CST 2021
     */
    public void setLastVersionId(String lastVersionId) {
        this.lastVersionId = lastVersionId == null ? null : lastVersionId.trim();
    }
}