package com.enn.energy.price.dal.po.mbg;

import java.util.Date;

public class SystemTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_tree.node_id
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    private Long nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_tree.node_name
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    private String nodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_tree.node_type
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    private String nodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_tree.business_type
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_tree.parent_id
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_tree.state
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_tree.create_time
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_tree.update_time
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_tree.node_id
     *
     * @return the value of system_tree.node_id
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public Long getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_tree.node_id
     *
     * @param nodeId the value for system_tree.node_id
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public void setNodeId(Long nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_tree.node_name
     *
     * @return the value of system_tree.node_name
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_tree.node_name
     *
     * @param nodeName the value for system_tree.node_name
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_tree.node_type
     *
     * @return the value of system_tree.node_type
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_tree.node_type
     *
     * @param nodeType the value for system_tree.node_type
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType == null ? null : nodeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_tree.business_type
     *
     * @return the value of system_tree.business_type
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_tree.business_type
     *
     * @param businessType the value for system_tree.business_type
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_tree.parent_id
     *
     * @return the value of system_tree.parent_id
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_tree.parent_id
     *
     * @param parentId the value for system_tree.parent_id
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_tree.state
     *
     * @return the value of system_tree.state
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_tree.state
     *
     * @param state the value for system_tree.state
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_tree.create_time
     *
     * @return the value of system_tree.create_time
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_tree.create_time
     *
     * @param createTime the value for system_tree.create_time
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_tree.update_time
     *
     * @return the value of system_tree.update_time
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_tree.update_time
     *
     * @param updateTime the value for system_tree.update_time
     *
     * @mbg.generated Fri Apr 29 17:39:44 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}